### ISSUE TITLE
smtp_client.dart _doEhloHelo error

### ISSUE THREAD

**Issue by NTMS2017** [kaisellgren/mailer#121]
Its was working since upgrade the plugin version 3.0.3 and today suddenly start to receive below error. I try to send mail to yahoo.co.uk and gmail and I got this error shown below.
What should I do, any idea?

**The Code:**
```
      String _username = "myusernamne@mycomany.com";
      String _password = "1q2w3e4a5s6d";

      final smtpServer = new SmtpServer('mail.mycomany.com',
          username: _username, 
          password: _password, 
          port: 25, 
          ignoreBadCertificate: true, 
          ssl: false, 
          allowInsecure: true);
```

**The error points the code**
```
try {
  final sendReports = await send(message, smtpServer);
```

**Error:**
```
E/flutter ( 6093): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Failed assertion: boolean expression must not be null
E/flutter ( 6093): #0      _doEhloHelo (package:mailer/src/smtp/smtp_client.dart:52:7)
E/flutter ( 6093): <asynchronous suspension>
E/flutter ( 6093): #1      connect (package:mailer/src/smtp/smtp_client.dart:131:11)
E/flutter ( 6093): <asynchronous suspension>
E/flutter ( 6093): #2      send (package:mailer/src/smtp/mail_sender.dart:93:26)
E/flutter ( 6093): #3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
E/flutter ( 6093): #4      send (package:mailer/src/smtp/mail_sender.dart:90:24)
E/flutter ( 6093): #5      _DekontPrintState._sendMail (package:myapp/ntms/dekont/dekont_print.dart:668:35)
E/flutter ( 6093): #6      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
E/flutter ( 6093): #7      _DekontPrintState._sendMail (package:myapp/ntms/dekont/dekont_print.dart:364:19)
E/flutter ( 6093): #8      _DekontPrintState._buildMailLayout.<anonymous closure>.<anonymous closure> (package:myapp/ntms/dekont/dekont_print.dart:922:25)
E/flutter ( 6093): #9      State.setState (package:flutter/src/widgets/framework.dart:1141:30)
E/flutter ( 6093): #10     _DekontPrintState._buildMailLayout.<anonymous closure> (package:myapp/ntms/dekont/dekont_print.dart:920:23)
```

**Comment by close2** [comment]
thanks for reporting

Do you know if your SMTP-server allows EHLO?
Is this a public SMTP-server or a private / company server?

I am pretty sure that this bug happens, when the server doesn't support EHLO.

Fix should come in a few days.
