### ISSUE TITLE
Receiving Exception after sending mail. [Required Assistance]

### ISSUE THREAD

**Issue by ritvij-saxena** [kaisellgren/mailer#142]
Using this code with my data.

```dart
final smtpServer = gmail(username, password);
  // Use the SmtpServer class to configure an SMTP server:
  // final smtpServer = SmtpServer('smtp.domain.com');
  // See the named arguments of SmtpServer for further configuration
  // options.  
  
  // Create our message.
  final message = Message()
    ..from = Address(username, 'Your name')
    ..recipients.add('destination@example.com')
    ..ccRecipients.addAll(['destCc1@example.com', 'destCc2@example.com'])
    ..bccRecipients.add(Address('bccAddress@example.com'))
    ..subject = 'Test Dart Mailer library :: 😀 :: ${DateTime.now()}'
    ..text = 'This is the plain text.\nThis is line 2 of the text part.'
    ..html = "<h1>Test</h1>\n<p>Hey! Here's some HTML content</p>";

  try {
    final sendReport = await send(message, smtpServer);
    print('Message sent: ' + sendReport.toString());
  } on MailerException catch (e) {
    print('Message not sent.');
    for (var p in e.problems) {
      print('Problem: ${p.code}: ${p.msg}');
    }
  }
```

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid message.
E/flutter (26198): #0      _validate (package:mailer/src/smtp/mail_sender.dart:118:5)
E/flutter (26198): #1      send (package:mailer/src/smtp/mail_sender.dart:92:3)
I/flutter (26198): Message sent: Message successfully sent.
I/flutter (26198): Connection was opened at: 2020-07-11 13:57:29.902698.
I/flutter (26198): Sending the message started at: 2020-07-11 13:57:30.623322 and finished at: 2020-07-11 13:57:31.082250.

Required Assistance. Any help would be greatly appreciated.

**Comment by close2** [comment]
Please enable logging:

```dart
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```
mailer thinks that the message is invalid.  The log output will tell you why.

**Comment by ritvij-saxena** [comment]
Can you tell me where I can find this package 'Logger' from?

**Comment by close2** [comment]
`  logging: '>0.0.1 <1.0.0'`
Look in the example directory.  The gmail.dart does use the logger.

**Comment by close2** [comment]
Please reopen if this is a bug in mailer.

**Comment by ritvij-saxena** [comment]
This is the log that I am receiving 
>SEVERE: 2020-08-05 16:11:55.342701: Message validation error: Envelope mail address is invalid.  null|The from address is invalid.  (Instance of 'Address')

Code: 
```
String username = SEND_GRID_USERNAME;
String password = SEND_GRID_PASSWORD;
final smtpServer = SmtpServer(SEND_GRID_URL, username: username, password: password);
    print(smtpServer);
    final message = new Message()
      ..from =
          new Address(username, <physical-address>)
      ..recipients.add('<rec1>')
      ..ccRecipients.addAll(['<rec2>'])
      ..subject = 'My subject'
      ..text = 'text! \n\n'
      ..html = '<p>Order #${order.id.toString()} is ready for delivery\n<br>'
          '\nCustomer Name: ${order.shipping.first_name + ' ' + order.shipping.last_name}'
          '<br>\nAddress: ${order.shipping.address_1 + ' ' + order.shipping.address_2 + ' ' + order.shipping.city + ' ' + order.shipping.postcode + ' ' + order.shipping.country}'
          '\n<br>Delivery: sometime soon</p>';
//      ..html = '&quot;Test\n<p>Hey! Here\'s some HTML content</p>&quot';
    print('almost done');
    final sendReports = await send(message, smtpServer);
    print(sendReports.toString());
    print('logs');
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    })
```

**Comment by ritvij-saxena** [comment]
In 
```
final message = new Message()
      ..from =
          new Address(**username** ....
```
the username value was wrong, it was expected to be an email id, followed by the label, hence invalid message exception.
Thank you for all the help.!
