### ISSUE TITLE
Unsupported operation: Socket constructor

### ISSUE THREAD

**Issue by casetofon** [kaisellgren/mailer#144]
Tried it on flutter web but instead of the email, I got this in the debug console: 

```
Error: Unsupported operation: Socket constructor
    at Object.throw_ [as throw] (http://localhost:56809/dart_sdk.js:4327:11)
    at Function._connect (http://localhost:56809/dart_sdk.js:57941:17)
    at Function.connect (http://localhost:56809/dart_sdk.js:57924:26)
    at connection.Connection.new.connect (http://localhost:56809/packages/mailer/src/smtp/connection.dart.lib.js:169:44)
    at connect.next (<anonymous>)
    at runBody (http://localhost:56809/dart_sdk.js:37602:34)
    at Object._async [as async] (http://localhost:56809/dart_sdk.js:37633:7)
    at connection.Connection.new.connect (http://localhost:56809/packages/mailer/src/smtp/connection.dart.lib.js:163:20)
    at connect (http://localhost:56809/packages/mailer/src/smtp/smtp_client.dart.lib.js:104:17)
    at connect.next (<anonymous>)
    at runBody (http://localhost:56809/dart_sdk.js:37602:34)
    at Object._async [as async] (http://localhost:56809/dart_sdk.js:37633:7)
    at Object.connect (http://localhost:56809/packages/mailer/src/smtp/smtp_client.dart.lib.js:101:18)
    at send (http://localhost:56809/packages/mailer/src/smtp/mail_sender.dart.lib.js:134:43)
    at send.next (<anonymous>)
    at runBody (http://localhost:56809/dart_sdk.js:37602:34)
    at Object._async [as async] (http://localhost:56809/dart_sdk.js:37633:7)
    at Object.send (http://localhost:56809/packages/mailer/src/smtp/mail_sender.dart.lib.js:132:18)
    at sender (http://localhost:56809/packages/webapp/com/mail.dart.lib.js:31:45)
    at sender.next (<anonymous>)
    at runBody (http://localhost:56809/dart_sdk.js:37602:34)
    at Object._async [as async] (http://localhost:56809/dart_sdk.js:37633:7)
    at Object.sender (http://localhost:56809/packages/webapp/com/mail.dart.lib.js:17:18)
    at http://localhost:56809/packages/webapp/pages/home.dart.lib.js:1745:23
    at Generator.next (<anonymous>)
    at runBody (http://localhost:56809/dart_sdk.js:37602:34)
    at Object._async [as async] (http://localhost:56809/dart_sdk.js:37633:7)
    at ink_well._InkResponseStateWidget.new.<anonymous> (http://localhost:56809/packages/webapp/pages/home.dart.lib.js:1744:77)
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:56809/packages/flutter/src/material/icon_button.dart.lib.js:46755:21)
    at http://localhost:56809/packages/flutter/src/material/icon_button.dart.lib.js:46856:734
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:56809/packages/flutter/src/gestures/recognizer.dart.lib.js:189:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:56809/packages/flutter/src/gestures/tap.dart.lib.js:353:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:56809/packages/flutter/src/gestures/tap.dart.lib.js:190:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:56809/packages/flutter/src/gestures/tap.dart.lib.js:167:23)
    at arena.GestureArenaManager.new.sweep (http://localhost:56809/packages/flutter/src/gestures/arena.dart.lib.js:208:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:56809/packages/flutter/src/gestures/binding.dart.lib.js:170:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:56809/packages/flutter/src/gestures/binding.dart.lib.js:149:24)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (http://localhost:56809/packages/flutter/src/gestures/binding.dart.lib.js:120:14)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:56809/packages/flutter/src/gestures/binding.dart.lib.js:93:34)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:56809/packages/flutter/src/gestures/binding.dart.lib.js:83:65)
    at Object._invoke1 (http://localhost:56809/dart_sdk.js:174905:7)
    at _engine.EngineWindow.new.invokeOnPointerDataPacket (http://localhost:56809/dart_sdk.js:170920:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:56809/dart_sdk.js:144505:24)
    at http://localhost:56809/dart_sdk.js:144892:26
    at http://localhost:56809/dart_sdk.js:144851:16
```

**Comment by close2** [comment]
Please see
https://github.com/kaisellgren/mailer/issues/136

(my first response is incorrect, but I give more information in my second response.)
