### ISSUE TITLE
How to use send_gmail.dart which updated recently?

### ISSUE THREAD

**Issue by NTMS2017** [kaisellgren/mailer#167]
Hi,

My last mailer plugin was 3.0. After flutter sdk 2 I try to update my project. I am failed to send mail. my mail pop and imap are enable and active. 

I try to see below example but I couldn't see where I can put my mail so I can't send myself. I can't use XOAUTH2 because seems too expensive for me.

Any idea how to use below example so I can send myself a mail. Where I can put my user name and password?

https://github.com/kaisellgren/mailer/blob/master/example/send_gmail.dart or
https://github.com/kaisellgren/mailer/blob/master/example/gmail_xoauth2/send_mail.dart

**Comment by NTMS2017** [comment]
In https://pub.dev/packages/mailer examples also gave me an error:

**ERROR:**
```
/Users/*********/flutter/bin/cache/dart-sdk/bin/dart --enable-asserts /Users/*********/IdeaProjects/ntms_gmail_xoauth2/bin/main.dart
Message not sent.
Unhandled exception:
Incorrect username / password / credentials
#0      _doAuthentication (package:mailer/src/smtp/smtp_client.dart:108:5)
<asynchronous suspension>
#1      connect (package:mailer/src/smtp/smtp_client.dart:137:5)
<asynchronous suspension>
#2      send (package:mailer/src/smtp/mail_sender.dart:91:20)
<asynchronous suspension>
#3      main (file:///Users/niyazitoros/IdeaProjects/ntms_gmail_xoauth2/bin/main.dart:63:23)
<asynchronous suspension>

Process finished with exit code 255
```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.2 at /Users/*********/flutter
    • Framework revision 8962f6dc68 (8 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/**********/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/************/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.7759

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

**Comment by close2** [comment]
new version scheduled for this week will fix this.

**Comment by NTMS2017** [comment]
Thank you. 🙏
