### ISSUE TITLE
Class 'SmtpClient' has no instance getter 'CryptoUtils'

### ISSUE THREAD

**Issue by ScottPierce** [kaisellgren/mailer#25]
I'm trying to send an email from a dart command line app, and it's failing with the following error:

```
Error occurred: Failed to send an email: Class 'SmtpClient' has no instance getter 'CryptoUtils'.

NoSuchMethodError: method not found: 'CryptoUtils'
Receiver: Instance of 'SmtpClient'
Arguments: []
```

**Comment by spierce7** [comment]
I was able to get the stacktrace:

```
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      SmtpClient._actionAuthenticateLoginUser (package:mailer/src/smtp/smtp_client.dart:252:17)
#3      SmtpClient._onData (package:mailer/src/smtp/smtp_client.dart:153:23)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1075)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#7      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:760)
#8      _StreamController._add (dart:async/stream_controller.dart:632)
#9      _StreamController.add (dart:async/stream_controller.dart:578)
#10     _Socket._onData (dart:io-patch/socket_patch.dart:1648)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1075)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#14     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:760)
#15     _StreamController._add (dart:async/stream_controller.dart:632)
#16     _StreamController.add (dart:async/stream_controller.dart:578)
#17     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:959)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by kaisellgren** [comment]
Hi.

I am a bit busy at the moment. I'll try to look at this during this week,
but if you happen to fix it I can merge a pull request.

**Comment by spierce7** [comment]
@kaisellgren I submitted a PR for this issue here: https://github.com/kaisellgren/mailer/pull/26

**Comment by danrubel** [comment]
This should be addressed by https://github.com/kaisellgren/mailer/commit/9221b75ed26a098a0af4ac984c8364535a522b8a
I'm working towards publishing mailer 1.1.0 over the next several weeks.

Please reopen if this does not address your concerns.
Thanks!
