### ISSUE TITLE
The getter 'path' was called on null error....

### ISSUE THREAD

**Issue by NTMS2017** [kaisellgren/mailer#89]
It was working few hours ago. But now I am stuck with this error. Any idea how to overcome from this issue?

**This is my original file after crop operation**
`I/flutter (  902): ======_backImageFile=======: File: '/data/user/0/com.capital_prime/cache/image_crop_7c0a78f8-9110-4d16-bb75-fd033dfc0fed5185917804655458468.jpg'`

**Before I construct mail I check if my file exist and prints the above.** 
**Error:**
```
E/flutter (  902): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'path' was called on null.
E/flutter (  902): Receiver: null
E/flutter (  902): Tried calling: path
E/flutter (  902): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter (  902): #1      new FileAttachment (package:mailer/src/entities/attachment.dart:39:52)
```

**initState code:**
```
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    mailSent = false;
    if (this.mounted) {
      setState(() {
        _backImageFile = widget.backImage;
       print("======_backImageFile=======: $_backImageFile);
      });
    }
  }

```
**Attachment code part:**
```
..attachments.add(new FileAttachment(_backImageFile)
        ..location = Location.inline
        ..cid = 'FileBack')
```

**Comment by close2** [comment]
This is the code, which throws an exception (the last line)
```dart
class FileAttachment extends Attachment {
  final File _file;

  FileAttachment(this._file, {String contentType, String fileName}) {
    if (contentType == null) {
      this.contentType = mime.lookupMimeType(_file.path);
```
Note that _file is directly set in the constructor.  Could you please verify again, that `_backImageFile` is not `null`.

In case I am currently not understanding my code and _backImageFile really is set you can prevent the line from being executed by setting the named argument `contentType`.

**Comment by NTMS2017** [comment]
Thank you very much. I am not sure if this is related to contentType or similar. I am guessing the file path didn't use future and await. So I change the init and add a Future with await to check if file exist. And it worked. Here is the code:

**initState()**
```
@override
void initState() {
  // TODO: implement initState
  super.initState();
  mailSent = false;

  if (this.mounted) {
    setState(() {
      _amount = getDecimalPlaces(widget.amaount);
      _vade = widget.vade;
      _cep = widget.cep;
      _bankName = widget.bankName;
      //_frontImageFile = widget.frontImage;
      //_backImageFile = widget.backImage;
      //_realImageFile = widget.realImage;

    });
  }
  _checkFileExist();
}

```

**Check if file exist before attach to mail:**
```
Future _checkFileExist() async {

  // ID CARD FRONT IMAGE -------------------------------------
  bool fileExistsFront = await widget.frontImage.existsSync();
  setState(() {
    if (fileExistsFront == true) {
      _frontImageFile = widget.frontImage;
      print("frontImageFile exist: $fileExistsFront");
    } else {
      _frontImageFile = null;
      print("frontImageFile exist: $fileExistsFront");
    }
  });
  // ---------------------------------------------------------


  // ID CARD BACK IMAGE --------------------------------------
  bool fileExistsBack = await widget.backImage.existsSync();
  setState(() {
    if (fileExistsBack == true) {
      _backImageFile = widget.backImage;
      print("backImageFile exist: $fileExistsBack");
    } else {
      _backImageFile = null;
      print("backImageFile exist: $fileExistsBack");
    }
  });
  // ---------------------------------------------------------


  // ID CARD REAL IMAGE --------------------------------------
  bool fileExistsReal = await widget.realImage.existsSync();
  setState(() {
    if (fileExistsReal == true) {
      _realImageFile = widget.realImage;
      print("realImageFile exist: $fileExistsReal");
    } else {
      _realImageFile = null;
      print("realImageFile exist: $fileExistsReal");
    }
  });
  // ---------------------------------------------------------

}
```


**Working Result:**
```
I/flutter (23427): frontImageFile exist: true
I/flutter (23427): _frontImageFile: File: '/data/user/0/com.capital_prime/cache/image_crop_faa73287-a310-4979-a426-9beb2980877d5315619855657348217.jpg'

I/flutter (23427): backImageFile exist: true
I/flutter (23427): _backImageFile: File: '/data/user/0/com.capital_prime/cache/image_crop_1ca7e2d8-d8f5-43f5-915c-6b17c0a81b6f6441797643651737057.jpg'

I/flutter (23427): realImageFile exist: true
I/flutter (23427): _realImageFile: File: '/data/user/0/com.capital_prime/cache/image_crop_3cf76fe9-4558-4731-8a96-a310673c8d6c5833733689416072401.jpg'







```

**Comment by close2** [comment]
There are some minor issues with your code.
You declare `_checkFileExists` as `async` but never `await` the result.
Fortunately `_checkFileExists` doesn't use any async function.
`existsSync` is a synchronous function and therefore doesn't require `await`.

As the definition of `initState` is not `async` there is no "easy" way to perform asynchronous calls in `initState`.  But again: you fortunately don't need any!

Your `_checkFileExists()` function should therefore look something like:
```dart
void _checkFileExist() {   // !!! Note that there is no future or async here !!!
  File checkFile(File f) => f?.existsSync() == true ? f : null;

  setState(() => _frontImageFile = checkFile(widget.frontImage));
  setState(() => _backImageFile = checkFile(widget.backImage));
  setState(() => _realImageFile = checkFile(widget.realImage));
}
```
